### ISSUE TITLE
What is it about

### ISSUE THREAD

**Issue by S-codes14** [PyMachine-Collective/Project-Genesis#1]
@shgnplaatjies I heard from the group, that you wanted to create some machine learning stuff, but what is project genesis about, or what are you going to create next, and how can we help

**Comment by shgnplaatjies** [comment]
Hi Sibongumusa

I’m currently taking part in an Android Hackathon.  I haven’t had time to
dedicate to the machine learning project. But I will on Monday and give a
project scope of work that needs to be complete and some ideas I have for
projects 👌🏾
